name: 'Johan&Sebastian'
favicon: null
layout_spectrum: 0.28859581984579563
typography_spectrum: 0.4120536600239575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.31097364984452724
  lightness: 0.701651823008433
  saturation: 0.7430536774918437
  rhythmicContrast: 0.2401491680648178
purpose: []
